#spring.datasource.url=jdbc:postgresql://localhost:5432/alapos_dev
#spring.datasource.username=alapos
#spring.datasource.password=K-m_13+a
#spring.jpa.hibernate.ddl-auto=none
#server.port = 8083

spring:
  profiles:
    active: de

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/alapos_dev
    username: alapos
    password: K-m_13+a
  jpa:
    hibernate:
      ddl-auto: none
  show-sql: true
#  jackson:
#    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug  
server:
  port: 8083
security:
  oauth2:
    resource:
      userInfoUri: https://192.168.71.120:8084/me
      
---
spring:
  profiles: de
  datasource:
    url: jdbc:postgresql://192.168.70.40:5432/alapos_dev
    username: alapos
    password: alapos
  jpa:
    hibernate:
      ddl-auto: none
  show-sql: true
#  jackson:
#    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug  
server:
  port: 8083
security:
  oauth2:
    resource:
      userInfoUri: http://192.168.71.120:8084/me
